"""create table SyncState

Revision ID: c4cea4f8b589
Revises: dcf5869bda38
Create Date: 2026-04-12 16:56:15.944932

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4cea4f8b589"
down_revision: Union[str, Sequence[str], None] = "dcf5869bda38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("sync_state",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("last_sync_time", sa.DateTime(timezone=True), nullable=True),
    sa.Column("sync_status", sa.Enum("IDLE", "RUNNING", "SUCCESS", "FAILED", name="syncstatus"), nullable=False),
    sa.Column("error_message", sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_state")
    # ### end Alembic commands ###
